# fly.toml app configuration file generated for lotto-journal-api

app = "lotto-journal-api"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  PORT = ":8080"
  R2_PUBLIC_URL_PREFIX = "https://lotto-cdn.theppitak.work"

[deploy]
  release_command = "sh -c 'exec /app/migrate -path /app/migrations -database \"$DB_DSN\" up'"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  # [[http_service.checks]]
  #   grace_period = "20s"
  #   interval = "15s"
  #   method = "GET"
  #   timeout = "5s"
  #   path = "/health"

  #   [http_service.checks.headers]
  #     X-Health-Check = "fly"
